server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cleaningservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Redneedle-21
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

app:
  jwtSecret: mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForSecurity
  jwtExpirationMs: 86400000
  cors:
    allowedOrigins: http://localhost:4200

logging:
  level:
    com.adao: DEBUG
    org.springframework.security: DEBUG

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cleaningservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: Redneedle-21
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

app:
  jwtSecret: mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForSecurity
  jwtExpirationMs: 86400000
  cors:
    allowedOrigins: "http://localhost:4200,http://127.0.0.1:4200"

logging:
  level:
    com.adao: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Production profile
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: never

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/cleaningservice?useSSL=true&serverTimezone=UTC
    username: root
    password: Redneedle-21
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true

app:
  jwtSecret: ${JWT_SECRET:your_very_secure_jwt_secret_key_here}
  jwtExpirationMs: 86400000
  cors:
    allowedOrigins: ${CORS_ORIGINS:https://yourdomain.com}

logging:
  level:
    com.adao: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  file:
    name: logs/cleaningservice.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
